flask:
  image: srinivasedugutta/flask-mysql-app:latest
  container_name: two-tier-app
  ports:
    - "5000:5000"
  environment:
    DB_HOST: mysql
    DB_USER: root
    DB_PASSWORD: root
    DB_NAME: devops
  depends_on:
    - mysql
  networks:
    - two-tier
